### ISSUE TITLE
Saved SQL queries

### ISSUE THREAD

**Issue by pavpanchekha** [mwillsey/crossbot#24]
Now that there is this SQL query interface, it would be great if some of our better queries could be easily saved and reused. I could imagine an interface like this:

- `cb sql --save <name> <query ....>` saves the query under a fixed name. If a binding for that name already exists probably best to override.
- `cb saved <name>` runs a saved query, or prints an error message if none exists.

**Comment by mwillsey** [comment]
Closed by #25
